### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by rimmeh8** [nitsan-technologies/ns_friendlycaptcha#12]
Typo3: 12.4.6
Php: 8.1

Sitekey and Secret Key insterted correctly but there is an Error establishing the Connection:

Verification failed
Connection problem with https://eu-api.friendlycaptcha.eu/api/v1/siteverify

**Comment by nitsan-technologies** [comment]
Hey @rimmeh8 

This is the configuration issue.  

By default, the "Enable EU endpoint" option is selected from the Extension Configuration. This option works only when your account is upgraded in the friendly captcha. 

Please uncheck the "Enable EU endpoint"  option and check the captcha.


![screenshot_11](https://github.com/nitsan-technologies/ns_friendlycaptcha/assets/2622317/9fa77228-c31c-4fb4-90bf-2caf686d01f6)


Please feel free to write us back if you need any more help.

Cheers, Team@NITSAN
