### ISSUE TITLE
Extension disables CSP without asking and documentation-hint

### ISSUE THREAD

**Issue by christophs78** [nitsan-technologies/ns_friendlycaptcha#15]
With https://github.com/nitsan-technologies/ns_friendlycaptcha/commit/ebc1ad60e51070ec6c87cc4839729d0a9b7559fd#diff-5e15ae082e9095bfca62c8b83a7a2cdbcf8e5ac4c750ab8c832aa12cce7d7a74R14 you disable CSP for front- and backend.

This

1. causes confusion until we figured out why enabling CSP via additional.php does not work
2. is in generall only a work-around and not a solution

Maybe you already tried to find a solution for this but failed within your time-constraints.

We will try to come up with suggestions as soon as we have some working ideas on our side.

**Comment by nitsan-technologies** [comment]
Hey @christophs78 

Thank you for pointing this out! We apologize for the delay in addressing the CSP issue. The issue has now been fixed in the latest update. We appreciate your understanding and look forward to any suggestions you may have.


Best Regards,
Team NITSAN
