### ISSUE TITLE
Compatibility with PHP 7.2

### ISSUE THREAD

**Issue by nitsan-technologies** [nitsan-technologies/ns_friendlycaptcha#5]
**System Environment**
TYPO3 9.5.8 and PHP 7.2.34. 

```
syntax error, unexpected 'CaptchaService' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

in /var/www/vhosts/wwjacob.de/httpdocs/websites/www/htdocs/typo3conf/ext/ns_friendlycaptcha/Classes/ViewHelpers/Form/RecaptchaViewHelper.php line 10
use TYPO3\CMS\Fluid\ViewHelpers\Form\AbstractFormFieldViewHelper;

class RecaptchaViewHelper extends AbstractFormFieldViewHelper
{
protected CaptchaService $captchaService;

public function __construct(CaptchaService $captchaService)
{
$this->captchaService = $captchaService;
```

**Comment by nilesh-nitsan** [comment]
Hi @nitsan-technologies, 
There are not any issues caused. So you may close this. We have checked in the given environment.

**Comment by jaumepresaspuig** [comment]
Hi, I am having the same issue in the file ns_friendlycaptcha/Classes/Adapter/TypoScriptAdapter.php.

TYPO3 10.4.14
PHP 7.2.34
ns_friendlycaptcha 1.3.3

It looks like the fix here ( https://github.com/nitsan-technologies/ns_friendlycaptcha/commit/5ef22a2c3902cdf2c59783526abf6eaaa83b216d ) has been done only for the version 12.*, not 1.*.
