### ISSUE TITLE
Enabling the EU endpoint

### ISSUE THREAD

**Issue by nitsan-technologies** [nitsan-technologies/ns_friendlycaptcha#7]
There is just one feature of Friendly Captcha I am missing in the extension. It is possible to define a EU endpoint for the frontend and also for backend verification. The reason is data privacy / GDPR. The documentation can be found here: https://docs.friendlycaptcha.com/#/eu_endpoint

Is it possible to include this in the extension as a possibility to activate the EU endpoint?

**Comment by nitsan-technologies** [comment]
Hey Community,

The feature has been release in v1.3.0 https://github.com/nitsan-technologies/ns_friendlycaptcha/releases/tag/1.3.0

Cheers, Team NITSAN

**Comment by benedikt-dreier** [comment]
Dear Team NITSAN,

I think the verification Link for the EU endpoint is wrong. Should be
`$verifyServerInfo = 'https://eu-api.friendlycaptcha.eu/api/v1/siteverify';`

but is:
`$verifyServerInfo = 'https://eu-api.friendlycaptcha.eu/api/v1/puzzle';`

Best regards
